apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: ${CRON_NAME}
objects:
  - apiVersion: batch/v1
    kind: CronJob
    metadata:
      name: ${CRON_NAME}
    spec:
      schedule: ${CRON_SCHEDULE}
      concurrencyPolicy: 'Forbid'
      suspend: false
      jobTemplate:
        spec:
          template:
            metadata:
              labels:
                app: ${CRON_NAME}
            spec:
              containers:
                - name: ${CRON_NAME}
                  image: image-registry.apps.silver.devops.gov.bc.ca/6cdc9e-tools/eagle-cron:latest
                  env:
                    - name: API_KEY
                      valueFrom:
                        secretKeyRef:
                          key: INTERNAL_API_KEY
                          name: ${API_KEY_SECRET_NAME}
                  volumeMounts:
                    - mountPath: /scripts
                      name: cron-configmap
              restartPolicy: Never
              volumes:
                - configMap:
                    defaultMode: 420
                    name: ${CONFIGMAP_NAME}
                  name: cron-configmap
parameters:
  - name: CRON_SCHEDULE
    description: 'Cron-like schedule expression. Default: Once every 30 minutes'
    value: '*/30 * * * *'
  - name: CRON_NAME
    description: 'Name of the cronjob container.'
    value: 'eagle-cron'
  - name: CONFIGMAP_NAME
    description: 'Name of the ConfigMap containing the cron scripts to mount'
    value: 'cron-config'
  - name: API_KEY_SECRET_NAME
    description: 'Name of the Secret containing INTERNAL_API_KEY for cron authentication'
    value: 'eagle-cron-secret'
