apiVersion: v1
kind: Template
metadata:
  name: eagle-cron
objects:
  - apiVersion: v1
    data:
      KEYCLOAK_CLIENT_ID: ${KEYCLOAK_CLIENT_ID}
      KEYCLOAK_CLIENT_SECRET: ${KEYCLOAK_CLIENT_SECRET}
      KEYCLOAK_REALM: ${KEYCLOAK_REALM}
      KEYCLOAK_URL: ${KEYCLOAK_URL}
    kind: Secret
    metadata:
      name: eagle-cron-keycloak
    type: Opaque
parameters:
  - name: 'KEYCLOAK_CLIENT_ID'
    required: true
  - name: 'KEYCLOAK_CLIENT_SECRET'
    required: true
  - name: 'KEYCLOAK_REALM'
    required: true
  - name: 'KEYCLOAK_URL'
    required: true
