apiVersion: v1
kind: Template
metadata:
  name: eagle-cron
objects:
  - apiVersion: image.openshift.io/v1
    kind: ImageStream
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewBuild
      creationTimestamp: null
      labels:
        build: eagle-cron
      name: eagle-cron
    spec:
      lookupPolicy:
        local: false
    status:
      dockerImageRepository: ''
  - apiVersion: build.openshift.io/v1
    kind: BuildConfig
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewBuild
      creationTimestamp: null
      labels:
        build: eagle-cron
      name: eagle-cron
    spec:
      nodeSelector: null
      output:
        to:
          kind: ImageStreamTag
          name: eagle-cron:latest
      postCommit: {}
      resources:
        requests:
          cpu: 1
        limits:
          cpu: 1
      source:
        contextDir: openshift/templates/jobs/cron/docker
        git:
          uri: https://github.com/bcgov/eagle-api
          ref: develop
        type: Git
      strategy:
        dockerStrategy:
          from:
            kind: ImageStreamTag
            name: 'ubi:8.3-227'
        type: Docker
      triggers:
        - type: ConfigChange
        - imageChange: {}
          type: ImageChange
