sync:
  image:
    tag: test

reindex:
  image:
    tag: test

typesense:
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 4Gi

cleanup:
  image:
    tag: test

contentExtract:
  enabled: true
  image:
    tag: test
  minioSecret:
    name: nr-object-store-credential
    hostKey: endpoint_url
    accessKeyKey: user_account
    secretKeyKey: password
    bucketKey: bucket_name
