sync:
  image:
    tag: dev

reindex:
  image:
    tag: dev

typesense:
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 4Gi

cleanup:
  image:
    tag: dev

contentExtract:
  enabled: true
  image:
    tag: dev
