# action.yml
name: 'Mongo Automated Migration'
description: 'Execute migrations to the MongoDB pod'
inputs:
  OC_URL:
    description: 'URL for Openshift'
    required: true
    default: 'https://console.pathfinder.gov.bc.ca:8443'
  OC_TOKEN:
    description: 'Token for executing oc commands'
    required: true
  ROCKETCHAT_WEBHOOK:
    description: 'Webhook for sending status to Rocketchat'
    required: true
  NAMESPACE:
    description: '6cdc9e-dev/6cdc9e-test/6cdc9e-prod'
    required: true
    default: '6cdc9e-dev'
runs:
  using: 'docker'
  image: 'Dockerfile'