apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: mongodb-40-build
  annotations:
    description: "BuildConfig for MongoDB 4.0.28 custom image for OpenShift"
    tags: "database,mongodb"
objects:
  - apiVersion: image.openshift.io/v1
    kind: ImageStream
    metadata:
      name: mongodb-40
      labels:
        app: mongodb
        version: "4.0"
    spec:
      lookupPolicy:
        local: false

  - apiVersion: build.openshift.io/v1
    kind: BuildConfig
    metadata:
      name: mongodb-40
      labels:
        app: mongodb
        version: "4.0"
    spec:
      output:
        to:
          kind: ImageStreamTag
          name: mongodb-40:4.0.28
      source:
        type: Git
        git:
          uri: ${GIT_REPO_URL}
          ref: ${GIT_REF}
        contextDir: openshift/templates/mongodb
      strategy:
        type: Docker
        dockerStrategy:
          dockerfilePath: Dockerfile
      triggers:
        - type: ConfigChange
        - type: ImageChange

parameters:
  - name: GIT_REPO_URL
    displayName: Git Repository URL
    description: The URL of the repository with the Dockerfile
    required: true
    value: https://github.com/bcgov/eagle-api.git

  - name: GIT_REF
    displayName: Git Reference
    description: Set this to a branch name, tag or commit SHA
    required: true
    value: develop
