# This action will create a Pull Request to merge all changes on TEST
# into the MASTER branch. PR will be created as a draft
name: Create master branch PR

on:
  pull_request:
    branches:
    - test
    types: [closed]

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: pull-request
      uses: repo-sync/pull-request@v2
      with:
        destination_branch: "master"
        pr_title: "Pulling ${{ github.ref }} into MASTER"
        pr_body: ":crown: *An automated PR*  This PR will pull all recent merges from TEST into MASTER"
        pr_label: "auto-pr from test to master" 
        pr_draft: true
        github_token: ${{ secrets.GITHUB_TOKEN }}