name: Trigger Prod Deploy Workflow

on:
  push:
    branches:
      - promotion/prod
    paths:
      - state.json

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          event-type: trigger-prod-deploy